C:/pspsdk/bin/make clean
cd vlf
bin2c vlf.prx vlf_prx.h vlf_prx
bin2c intra.prx intra.h intra
bin2c iop.prx iop.h iop
cd ..
bin2c ..\data\divapatch.prx divapatch.h divapatch
bin2c ..\data\divaext_translation.bin divaext_translation.h divaext_translation
bin2c ..\data\diva2nd#_translation.bin diva2nd0_translation.h diva2nd0_translation
bin2c ..\data\divaext_images.bin divaext_images.h divaext_images
bin2c ..\data\divaext_embedded.bin divaext_embedded.h divaext_embedded
bin2c ..\data\divaext\font12dot_01.png font12dot_01.h font12dot_01
bin2c ..\data\divaext\menu_help_01.png menu_help_01.h menu_help_01
bin2c ..\data\divaext\menu_help_02.png menu_help_02.h menu_help_02
bin2c ..\data\divaext\menu_title_adhk.png menu_title_adhk.h menu_title_adhk
bin2c ..\data\divaext\menu_title_crsl.png menu_title_crsl.h menu_title_crsl
bin2c ..\data\divaext\menu_title_edit.png menu_title_edit.h menu_title_edit
bin2c ..\data\divaext\menu_title_home.png menu_title_home.h menu_title_home
bin2c ..\data\divaext\menu_title_modl.png menu_title_modl.h menu_title_modl
bin2c ..\data\divaext\menu_title_msbx.png menu_title_msbx.h menu_title_msbx
bin2c ..\data\divaext\menu_title_optn.png menu_title_optn.h menu_title_optn
bin2c ..\data\divaext\menu_title_plys.png menu_title_plys.h menu_title_plys
bin2c ..\data\divaext\menu_title_prvd.png menu_title_prvd.h menu_title_prvd
bin2c ..\data\divaext\menu_title_room.png menu_title_room.h menu_title_room
bin2c ..\data\divaext\menu_title_rtmg.png menu_title_rtmg.h menu_title_rtmg
bin2c ..\data\divaext\menu_title_shop.png menu_title_shop.h menu_title_shop
bin2c ..\data\divaext\menu_title_visl.png menu_title_visl.h menu_title_visl
bin2c ..\data\divaext\pv_rank_01.png pv_rank_01.h pv_rank_01
bin2c ..\data\divaext\pv_start_37.png pv_start_37.h pv_start_37
bin2c ..\data\divaext\pv_start_39.png pv_start_39.h pv_start_39
bin2c ..\data\divaext\pv_start_40.png pv_start_40.h pv_start_40
bin2c ..\data\divaext\pv_start_41.png pv_start_41.h pv_start_41
bin2c ..\data\divaext\pv_start_53.png pv_start_53.h pv_start_53
bin2c ..\data\divaext\pv_start_65.png pv_start_65.h pv_start_65
bin2c ..\data\divaext\pv_start_67.png pv_start_67.h pv_start_67
bin2c ..\data\divaext\pv_start_68.png pv_start_68.h pv_start_68
bin2c ..\data\divaext\pv_start_69.png pv_start_69.h pv_start_69
bin2c ..\data\divaext\pv_start_70.png pv_start_70.h pv_start_70
bin2c ..\data\divaext\pv_start_71.png pv_start_71.h pv_start_71
bin2c ..\data\divaext\pv_start_72.png pv_start_72.h pv_start_72
bin2c ..\data\divaext\pv_start_73.png pv_start_73.h pv_start_73
bin2c ..\data\divaext\pv_start_74.png pv_start_74.h pv_start_74
bin2c ..\data\divaext\pv_start_75.png pv_start_75.h pv_start_75
bin2c ..\data\divaext\pv_start_76.png pv_start_76.h pv_start_76
bin2c ..\data\divaext\pv_start_77.png pv_start_77.h pv_start_77
bin2c ..\data\divaext\pv_start_78.png pv_start_78.h pv_start_78
bin2c ..\data\divaext\pv_start_79.png pv_start_79.h pv_start_79
bin2c ..\data\divaext\pv_start_80.png pv_start_80.h pv_start_80
bin2c ..\data\divaext\pv_start_81.png pv_start_81.h pv_start_81
bin2c ..\data\divaext\pv_start_82.png pv_start_82.h pv_start_82
bin2c ..\data\divaext\pv_start_83.png pv_start_83.h pv_start_83
bin2c ..\data\divaext\pv_start_84.png pv_start_84.h pv_start_84
bin2c ..\data\divaext\pv_start_85.png pv_start_85.h pv_start_85
bin2c ..\data\divaext\pv_start_86.png pv_start_86.h pv_start_86
bin2c ..\data\divaext\pv_start_87.png pv_start_87.h pv_start_87
bin2c ..\data\divaext\pv_start_88.png pv_start_88.h pv_start_88
bin2c ..\data\divaext\pv_start_89.png pv_start_89.h pv_start_89
bin2c ..\data\divaext\pv_start_90.png pv_start_90.h pv_start_90
bin2c ..\data\divaext\pv_start_91.png pv_start_91.h pv_start_91
bin2c ..\data\divaext\pv_start_92.png pv_start_92.h pv_start_92
bin2c ..\data\divaext\pv_start_93.png pv_start_93.h pv_start_93
bin2c ..\data\divaext\pv_start_94.png pv_start_94.h pv_start_94
bin2c ..\data\divaext\pv_start_95.png pv_start_95.h pv_start_95
bin2c ..\data\divaext\pv_start_96.png pv_start_96.h pv_start_96
bin2c ..\data\divaext\pv_start_97.png pv_start_97.h pv_start_97
bin2c ..\data\divaext\pv_start_edit.png pv_start_edit.h pv_start_edit
bin2c ..\data\divaext\load_00.png load_00.h load_00
bin2c ..\data\divaext\load_01.png load_01.h load_01
bin2c ..\data\divaext\load_02.png load_02.h load_02
bin2c ..\data\divaext\load_03.png load_03.h load_03
bin2c ..\data\divaext\load_04.png load_04.h load_04
bin2c ..\data\divaext\load_05.png load_05.h load_05
bin2c ..\data\divaext\load_06.png load_06.h load_06
bin2c ..\data\divaext\load_07.png load_07.h load_07
bin2c ..\data\divaext\load_08.png load_08.h load_08
bin2c ..\data\divaext\load_09.png load_09.h load_09
bin2c ..\data\divaext\load_10.png load_10.h load_10
bin2c ..\data\divaext\load_11.png load_11.h load_11
bin2c ..\data\divaext\load_12.png load_12.h load_12
bin2c ..\data\divaext\load_13.png load_13.h load_13
bin2c ..\data\divaext\load_14.png load_14.h load_14
bin2c ..\data\divaext\load_15.png load_15.h load_15
bin2c ..\data\divaext\load_16.png load_16.h load_16
bin2c ..\data\divaext\load_17.png load_17.h load_17
bin2c ..\data\divaext\load_18.png load_18.h load_18
bin2c ..\data\divaext\load_19.png load_19.h load_19
bin2c ..\data\divaext\load_20.png load_20.h load_20
bin2c ..\data\divaext\load_21.png load_21.h load_21
bin2c ..\data\divaext\load_22.png load_22.h load_22
bin2c ..\data\divaext\load_23.png load_23.h load_23
bin2c ..\data\divaext\load_24.png load_24.h load_24
bin2c ..\data\divaext\load_25.png load_25.h load_25
bin2c ..\data\divaext\load_26.png load_26.h load_26
bin2c ..\data\divaext\load_27.png load_27.h load_27
bin2c ..\data\divaext\load_28.png load_28.h load_28
bin2c ..\data\divaext\load_29.png load_29.h load_29
bin2c ..\data\divaext\load_30.png load_30.h load_30
bin2c ..\data\divaext\load_31.png load_31.h load_31
bin2c ..\data\divaext\edit_base_04.png edit_base_04.h edit_base_04
bin2c ..\data\divaext\home_base_02.png home_base_02.h home_base_02
bin2c ..\data\divaext\menu_base_01.png menu_base_01.h menu_base_01
bin2c ..\data\divaext\menu_result.png menu_result.h menu_result
bin2c ..\data\divaext\mtit_base_01.png mtit_base_01.h mtit_base_01
bin2c ..\data\divaext\mtit_base_02.png mtit_base_02.h mtit_base_02
bin2c ..\data\divaext\mtit_base_03.png mtit_base_03.h mtit_base_03
bin2c ..\data\divaext\mtit_base_04.png mtit_base_04.h mtit_base_04
bin2c ..\data\divaext\mtit_base_05.png mtit_base_05.h mtit_base_05
bin2c ..\data\divaext\plst_base_01.png plst_base_01.h plst_base_01

C:/pspsdk/bin/make 
rm *.prx *.o *.elf *.sfo divapatch.h divaext_translation.h diva2nd0_translation.h divaext_images.h divaext_embedded.h font12dot_01.h menu_help_01.h menu_help_02.h menu_title_adhk.h menu_title_crsl.h menu_title_edit.h menu_title_home.h menu_title_modl.h menu_title_msbx.h menu_title_optn.h menu_title_plys.h menu_title_prvd.h menu_title_room.h menu_title_rtmg.h menu_title_shop.h menu_title_visl.h pv_rank_01.h pv_start_37.h pv_start_39.h pv_start_40.h pv_start_41.h pv_start_53.h pv_start_65.h pv_start_67.h pv_start_68.h pv_start_69.h pv_start_70.h pv_start_71.h pv_start_72.h pv_start_73.h pv_start_74.h pv_start_75.h pv_start_76.h pv_start_77.h pv_start_78.h pv_start_79.h pv_start_80.h pv_start_81.h pv_start_82.h pv_start_83.h pv_start_84.h pv_start_85.h pv_start_86.h pv_start_87.h pv_start_88.h pv_start_89.h pv_start_90.h pv_start_91.h pv_start_92.h pv_start_93.h pv_start_94.h pv_start_95.h pv_start_96.h pv_start_97.h pv_start_edit.h load_00.h load_01.h load_02.h load_03.h load_04.h load_05.h load_06.h load_07.h load_08.h load_09.h load_10.h load_11.h load_12.h load_13.h load_14.h load_15.h load_16.h load_17.h load_18.h load_19.h load_20.h load_21.h load_22.h load_23.h load_24.h load_25.h load_26.h load_27.h load_28.h load_29.h load_30.h load_31.h edit_base_04.h home_base_02.h menu_base_01.h menu_result.h mtit_base_01.h mtit_base_02.h mtit_base_03.h mtit_base_04.h mtit_base_05.h plst_base_01.h 
cd vlf
rm *.h
cd ..
pause